package my_custom_component;

import VASSAL.build.Buildable;
import VASSAL.build.GameModule;
import VASSAL.build.module.Chatter;
import VASSAL.build.module.Map;
import VASSAL.build.module.ModuleExtension;
import VASSAL.build.module.documentation.HelpFile;
import VASSAL.command.Command;
import VASSAL.command.CommandEncoder;
import VASSAL.command.NullCommand;
import VASSAL.command.RemovePiece;
import VASSAL.configure.IntConfigurer;
import VASSAL.counters.BasicPiece;
import VASSAL.tools.DataArchive;
import VASSAL.tools.JarArchive;

import javax.imageio.ImageIO;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.awt.image.BufferedImage;
import java.io.*;
import java.net.URL;
import java.util.List;
import java.util.*;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;


public final class AnimatedDice extends ModuleExtension implements CommandEncoder, Buildable{
    private GameModule gameModule;
    private DataArchive dataArchive;
    private JarArchive jar = new JarArchive();
    private String RED_DIE_FOLDER_PATH = "DiceImages/RED DIE/";
    private String HESITANT_RED_DIE_FOLDER_PATH = "DiceImages/HRED DIE/";
    private String WHITE_DIE_FOLDER_PATH = "DiceImages/WHITE DIE/";
    private String HESITANT_WHITE_DIE_FOLDER_PATH = "DiceImages/HWHITE DIE/";
    private String RED_HESITANT_DIE_INDEXES = "DiceImages/Hesitant Red Die Indexes.txt";
    private String WHITE_HESITANT_DIE_INDEXES = "DiceImages/Hesitant White Die Indexes.txt";
    private final String ANIMATED_DICE_PREFERENCES = "Animated 3D Dice";
    private final String FRAME_RATE_SETTINGS = "frameRateSettings";
    private final String DICE_POSITION_SETTINGS = "dicePositionSettings";
    private int dicePositionSettings;
    private int MAX_HORIZONTAL_OFFSET = 0;
    private int IMAGE_SIZE = 250;
    private boolean isImageVisible; // establish if last dice frame is still visible in the screen so that the button is in Hide mode.
    private boolean isAnimationInProgress = false; // prevents mousePress action before animation finishes.
    private JButton throwDieButton;
    private int[] mouseBiasFactor; // Set of ints generated by mouse movement which will influence dice results
    private final int NUMBER_OF_DICE = 2; // number of dices rolled
    private int NUMBER_OF_SIDES = 6; // number of sides of a die
    private long imageDelay; // The number of MILLISECONDS between the display actions.
    private int currentFrame;
    private int frameRate;
    private final int MAX_FRAME_RATE = 60;
    private final int MIN_FRAME_RATE = 35;
    private ScheduledExecutorService scheduler; // Controls the frame rate of the displayed images
    private List<Image> images; // to be fed with the dice images that will be drawn on the pieces
    private HashMap<String, HashMap<Integer, ArrayList<Image>>> preloadedImages; // set of preloaded images for each die and each result on the form: "Red": 6: List of images
    private java.util.Map<String, Image[]> diceImages;
    private int[] lastDiceImageFolderIndexes = new int[]{0,0}; // Keeps the last two dice image folders indexes stored to prevent immediate repetition of same animation
    private int lastNumberOfDiceRolled = 1;
    private HashMap<Integer, HashMap<Integer, ArrayList<Integer>>> redHesitantDieFolderBuilder; //Keep data taken from a txt file to reproduce the folder names for hesitant dice. Key: Animation number / Key: die result / value: rejected die value (middle number in folder name)
    private HashMap<Integer, HashMap<Integer, ArrayList<Integer>>> whiteHesitantDieFolderBuilder;
    private HashMap<String, Object[]> lastAnimationUsed; // Keeps track of the last animation used to prevent immediate repetition and to control hesitant dice probabilities. Must have the form ["Red", [4, true]] where true is for hesitant die
    private double hesitantDieProbability;
    private final int NUMBER_OF_DIE_ANIMATIONS = 27; // ALTER THAT IF MORE ANIMATIONS ARE ADEED
    private final int NUMBER_OF_HESITANT_DIE_ANIMATIONS = 5;
    private boolean feedingImages; // Checks if the thread for loading images is still running
    private byte[] dieAudioData;
    private byte[] diceAudioData;
    private byte[] shakingDiceAudioData;
    private boolean shouldStopFlag;
    private Cursor dieCursor;
    private boolean actionInProgress = false;
    private BasicPiece[] pieces; // pieces are added to this array to be displayed in order
    private final Map currentMap;

    public AnimatedDice(){
        super(GameModule.getGameModule().getDataArchive());
        isImageVisible = false;
        gameModule = GameModule.getGameModule();
        dataArchive = gameModule.getDataArchive();
        currentMap = GameModule.getGameModule().getComponentsOf(Map.class).get(0);
        dicePositionSettings = 0;
        frameRate = 45;
        currentFrame = 0;
        hesitantDieProbability = 0.3; // must be multiplied by animations Ratio to ge the actual probability
        lastAnimationUsed = new HashMap<String, Object[]>(){{
            put("white", new Object[]{0, false});
            put("red", new Object[]{0, false});
        }};
        // INITIALIZES THE PRELOADED IMAGES HASHMAP
        preloadedImages = new HashMap<>();
        preloadedImages.put("white", new HashMap<>());
        preloadedImages.put("red", new HashMap<>());
        for (int i = 1; i <= NUMBER_OF_SIDES; i++){
            preloadedImages.get("white").put(i, new ArrayList<>());
            preloadedImages.get("red").put(i, new ArrayList<>());
        }

        // CREATE THE ARRAY INDICATING WHAT FOLDERS BRING HESITANT DIE ANIMATIONS
        redHesitantDieFolderBuilder = CreateHesitantDieFolderBuilder(RED_HESITANT_DIE_INDEXES);
        whiteHesitantDieFolderBuilder = CreateHesitantDieFolderBuilder(WHITE_HESITANT_DIE_INDEXES);

        // GET RESOURCES
        loadSounds(); // Preloads sounds for dices

        URL iconURL = null;
        try {
            iconURL = dataArchive.getURL("Cursor/DieCursor.png");
            //System.out.println("icon URL: " + iconURL);
            BufferedImage dieCursorImage = ImageIO.read(iconURL);
            dieCursor = Toolkit.getDefaultToolkit().createCustomCursor(dieCursorImage, new Point(0,0), "Custom Die Cursor");
        } catch (IOException e) {
            System.out.println("Unable to load Icon image.");
            e.printStackTrace();
        }

        // LOAD FIRST SET OF IMAGES
        DrawDiceFolders();
    }

    public static void main(String[] args) {

    }


    @Override
    public void addTo(Buildable parent) {
        if (parent instanceof GameModule) {
            gameModule = (GameModule) parent;
            // Create your button instance
            throwDieButton = new DelayedActionButton("Roll Dice", new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    toggleImagesVisibility(1);
                }
            });
            throwDieButton.setToolTipText("Displays Image on map");

            // Add the button to the toolbar
            gameModule.getToolBar().add(throwDieButton);

            // ADD SETTINGS TO PREFERENCE WINDOW

            // FRAME RATE
            final IntConfigurer frameRateSettings = new IntConfigurer(FRAME_RATE_SETTINGS, "Frame Rate (MAX: " + MAX_FRAME_RATE + " / MIN: " + MIN_FRAME_RATE + ")", frameRate);
            gameModule.getPrefs().addOption(ANIMATED_DICE_PREFERENCES, frameRateSettings);
            frameRate = Integer.parseInt(gameModule.getPrefs().getValue(FRAME_RATE_SETTINGS).toString());

            frameRateSettings.addFocusListener(new FocusListener() {
                Object initialValue;
                @Override
                public void focusGained(FocusEvent e) {
                    initialValue = gameModule.getPrefs().getValue(FRAME_RATE_SETTINGS);
                }
                @Override
                public void focusLost(FocusEvent e) {
                    Object presentValue = gameModule.getPrefs().getValue(FRAME_RATE_SETTINGS);
                    if (Integer.parseInt(presentValue.toString()) > MAX_FRAME_RATE || Integer.parseInt(presentValue.toString()) < MIN_FRAME_RATE) {
                        gameModule.getPrefs().setValue(FRAME_RATE_SETTINGS, initialValue);
                    } else {
                        gameModule.getPrefs().setValue(FRAME_RATE_SETTINGS, presentValue);
                        frameRate = Integer.parseInt(gameModule.getPrefs().getValue(FRAME_RATE_SETTINGS).toString());
                    }
                }
            });


            // DICE POSITION
            MAX_HORIZONTAL_OFFSET = currentMap.getView().getMaximumSize().width; // IMPLEMENT!!

            final IntConfigurer dicePositionSettings = new IntConfigurer(DICE_POSITION_SETTINGS, "Screen Position (MAX: " + MAX_HORIZONTAL_OFFSET + " / MIN: " + 0 + ")", this.dicePositionSettings);
            gameModule.getPrefs().addOption(ANIMATED_DICE_PREFERENCES, dicePositionSettings);
            this.dicePositionSettings = Integer.parseInt(gameModule.getPrefs().getValue(DICE_POSITION_SETTINGS).toString());

            dicePositionSettings.addFocusListener(new FocusListener() {
                Object initialValue;

                @Override
                public void focusGained(FocusEvent e) {
                    initialValue = gameModule.getPrefs().getValue(DICE_POSITION_SETTINGS);
                }

                @Override
                public void focusLost(FocusEvent e) {
                    Object presentValue = gameModule.getPrefs().getValue(DICE_POSITION_SETTINGS);
                    if (Integer.parseInt(presentValue.toString()) > MAX_HORIZONTAL_OFFSET || Integer.parseInt(presentValue.toString()) < 0) {
                        gameModule.getPrefs().setValue(DICE_POSITION_SETTINGS, initialValue);
                    } else {
                        gameModule.getPrefs().setValue(DICE_POSITION_SETTINGS, presentValue);
                        AnimatedDice.this.dicePositionSettings = Integer.parseInt(gameModule.getPrefs().getValue(DICE_POSITION_SETTINGS).toString());
                    }
                }
            });
        }
    }

    private void loadSounds(){
        try {
            // Preload the audio data into memory
            InputStream dieSoundStream = dataArchive.getInputStream("DiceSounds/Selected1" + ".wav");
            InputStream diceSoundStream = dataArchive.getInputStream("DiceSounds/Selected2" + ".wav"); // For more than one die
            InputStream shakingDiceSoundStream = dataArchive.getInputStream("DiceSounds/Selected3" + ".wav"); // For shaking dice
            dieAudioData = dieSoundStream.readAllBytes();
            diceAudioData = diceSoundStream.readAllBytes();
            shakingDiceAudioData = shakingDiceSoundStream.readAllBytes();
            dieSoundStream.close();
            diceSoundStream.close();
            shakingDiceSoundStream.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private void playSounds(byte[] audioData){
        try{
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new ByteArrayInputStream(audioData));
            Clip clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            new Thread(() -> {
                clip.start();
                while (clip.getFramePosition() < clip.getFrameLength()){
                    if (shouldStopFlag)
                        clip.close();
                    Thread.yield();
                }
                clip.close();
                Thread.currentThread().interrupt();
            }).start();
            try{  // Works without the try block, but seems to delay the first use of sounds
                audioInputStream.close();
            } catch(IOException e){
                e.printStackTrace();
            }
        } catch (Exception e){
            System.out.println("Exception thrown");
            e.printStackTrace();
        }
        shouldStopFlag = false;
    }


    private void toggleImagesVisibility(int numberOfDice){
        // ENDS THE ANIMATION
        if (isImageVisible){
            throwDieButton.setEnabled(false);
            hideImage(pieces[pieces.length - 1]); // Hide last frame, which remained visible
            isImageVisible = false;
            // We definitely remove each piece so that no artifacts are presented on screen and load new images for each result
            try{
                new Thread(() -> {
                    for (BasicPiece piece: pieces){
                        Command remove = new RemovePiece(piece);
                        remove.execute();
                    }
                    //DrawDiceFolders();
                    while (feedingImages){
                        Thread.yield();
                    }
                    throwDieButton.setText("Roll Dice");
                    throwDieButton.setEnabled(true);
                    currentMap.getView().repaint();
                    System.out.println("Before toggleImages call inside toggleImages");
                    toggleImagesVisibility(1); // REMOVE LATER
                    System.out.println("AFTER toggleImages call inside toggleImages");
                    Thread.currentThread().interrupt();
                }).start();
            } catch (Exception e){
                System.out.println("Inside ToggleImagesVisibility. Exception while Resetting Roll Dice Button.");
                e.printStackTrace();
            }

        } else {
            // BEGINS THE ANIMATION
            isAnimationInProgress = true;
            throwDieButton.setEnabled(false);
            imageDelay = (1000/frameRate); // transform frame rate into milliseconds delay

            int[] results = RollDices (numberOfDice, NUMBER_OF_SIDES);
            createPieces("white", results[0]);
            scheduler = Executors.newSingleThreadScheduledExecutor();
            playSounds(dieAudioData);

            Rectangle rectangle = currentMap.getView().getVisibleRect();
            // If dicePosition (set up in preferences), which is the offset of the animation to the left,,
            // is larger than the width of the window minus the width of the images, we adjust it to the maximum place to which the animation may be offset without cropping the image.
            int adjustedDicePositionSettings = (dicePositionSettings > (rectangle.width - IMAGE_SIZE))? Math.max (rectangle.width - IMAGE_SIZE, 0): dicePositionSettings;
            int min_x = rectangle.x; // leftmost point of the current visible rectangle
            int x = (min_x + adjustedDicePositionSettings); // we add the adjusted offset to the leftmost point of the window.
            int y = rectangle.y;

            Runnable task = () -> displayImage(x,y);
            scheduler.scheduleAtFixedRate(task, 0, imageDelay, TimeUnit.MILLISECONDS);
        }
    }

    public void stopImageDisplay(){
        scheduler.shutdown();
        try{
            if (!scheduler.awaitTermination(1, TimeUnit.SECONDS)){
                scheduler.shutdownNow();
                throwDieButton.setEnabled(true);
                isAnimationInProgress = false;
            }
        } catch (InterruptedException ex){
            scheduler.shutdownNow();
            Thread.currentThread().interrupt();
        }
    }

    private void displayImage(int x, int y){
        if (currentMap != null){
            if (currentFrame == pieces.length) {
                stopImageDisplay();
                currentFrame = 0;
                isImageVisible = true; // can only set this to true after last image is displayed, since when the button is pressed again, the behavior depends on that variable.
                throwDieButton.setText("Hide Dice");

                System.out.println("before toggleImages call inside displayImages");
                toggleImagesVisibility(1); // REMOVE LATER
                System.out.println("After toggleImages call inside displayImages");
                return;
            }

            int xCoordinate = x;
            int yCoordinate = y;

            currentMap.placeAt(pieces[currentFrame], new Point(xCoordinate,yCoordinate));
            if (currentFrame > 1){
                currentMap.removePiece(pieces[currentFrame - 1]);
            }

            currentFrame = (currentFrame + 1);
        }
    }

    private void hideImage(BasicPiece piece) {
        if (currentMap != null) {
            currentMap.removePiece(piece);
            currentMap.repaint();
        }
    }

    private void createPieces(String die, int result){
        int numberOfPieces = preloadedImages.get(die).get(result).size();
        pieces = new BasicPiece[numberOfPieces];
        for (int i = 0; i < numberOfPieces; i++){
            final int index = i; // make index final, so it can be accessed from the inner class
            System.out.println("Before trying to print preloadedImage");
            System.out.println(preloadedImages.get(die).get(result).get(index));
            System.out.println("After printing preloaded image");
            BasicPiece piece = new BasicPiece() {
                private final Image image = preloadedImages.get(die).get(result).get(index);
                @Override
                public void draw(Graphics g, int x, int y, Component obs, double zoom) {
                    super.draw(g, x, y, obs, zoom);
                    // Draw the image at the specified (x, y) coordinates
                    g.drawImage(image, x, y, obs);
                }
            };
            pieces[i] = piece;
        }
        //PRELOAD NEXT IMAGES
        try{
            new Thread(() -> {
                feedingImages = true; // Set to false in DrawDiceFolders, after loading images has finished
                DrawDiceFolders();
               // while (feedingImages){
               //     Thread.yield();
                //}
                Thread.currentThread().interrupt();
            }).start();
        } catch (Exception e){
            System.out.println("Unable to preload images");
            e.printStackTrace();
        }
    }


    public void getImages(String path, String die, int result){
        diceImages = new HashMap<>();
        images = new ArrayList<>();
        int imageNumber = 0;
        Random random = new Random();
        System.out.println("Path: " + path);
        while (true) {
            try {
                URL imageURL = dataArchive.getURL(path + String.format("die%04d", imageNumber) + ".png");
               //System.out.println("Loading image: " + imageURL);
                preloadedImages.get(die).get(result).add(ImageIO.read(imageURL));
                imageNumber++;
            } catch (IOException e) {
                System.out.println("getImages Exception");
                break;
            }
        }
    }

    private void DrawDiceFolders(){
        System.out.println("BEGIN NEW DRAW");
        // Clears the previously preloaded images
        for (int i = 1; i <= NUMBER_OF_SIDES; i++){
            preloadedImages.get("white").put(i, new ArrayList<Image>());
            preloadedImages.get("red").put(i, new ArrayList<Image>());
        }
        double hesitantProb = hesitantDieProbability * (double)(NUMBER_OF_HESITANT_DIE_ANIMATIONS/NUMBER_OF_DIE_ANIMATIONS); // We must update it, since hesitantDieProbability may be changed in preference
        int hesitantDie = 1; // Red as default, so that if we have only one die, the code for normal animation will run for white;
        if((boolean) lastAnimationUsed.get("white")[1] || ((boolean) lastAnimationUsed.get("red")[1] && lastNumberOfDiceRolled == 2)) { // index 1 checks a boolean that is true if the last animation used for that die was a hesitant die animation. Only considers the red die case if it was included in the las toll.
            hesitantProb = hesitantProb * 0.3; // reduces the probability of a sequential hesitant die animation
        }
        Random random = new Random();
        hesitantProb = 1; // REMOVE LATER!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        if (random.nextDouble() < hesitantProb){ //Choose among hesitant die animations for red or white die
            /// REMEMBER TO ALTER BELOW TO NUMBER_OF_DICE
            hesitantDie = random.nextInt(1); // The die that will have the hesitant animation. 0 is white and 1 is red
            int animNumber; // there is no animation with index 0
            do {
                animNumber = random.nextInt(NUMBER_OF_HESITANT_DIE_ANIMATIONS) + 1; // there is no animation with index 0
            } while (animNumber == (int)lastAnimationUsed.get("white")[0] || animNumber == (int)lastAnimationUsed.get("red")[0]); // prevents immediate repetition of animation

            String folderPrefix = (hesitantDie == 0) ? HESITANT_WHITE_DIE_FOLDER_PATH : HESITANT_RED_DIE_FOLDER_PATH;

            for (int i = 1; i <= NUMBER_OF_SIDES; i++) {
                ArrayList<Integer> animVariations = (hesitantDie == 0) ?
                        whiteHesitantDieFolderBuilder.get(animNumber).get(i) :
                        redHesitantDieFolderBuilder.get(animNumber).get(i);

                StringBuilder path = new StringBuilder();
                path.append(folderPrefix).append((hesitantDie == 0) ? "W" : "R").append(animNumber).append("_")
                        .append(animVariations.get(random.nextInt(animVariations.size()))).append("_").append(i).append("/");
                //System.out.println(path);

                getImages(path.toString(), (hesitantDie == 0) ? "white" : "red", i);
            }


            lastAnimationUsed.put("white", new Object[]{animNumber, true});
        } else {

        }
        feedingImages = false; // Set to true in CreatePieces, after creation is finished and new feed from disk begins
        System.out.println("FINISHED DRAW");
    }

    private int[] RollDices (int numberOfDice, int numberOfSides){
        int[] unalteredRolls = DR(numberOfDice,numberOfSides);
        int[] alteredRolls = new int[unalteredRolls.length]; // Rolls after bias application

        for (int i = 0; i < unalteredRolls.length; i++){
            alteredRolls[i] = (unalteredRolls[i] + mouseBiasFactor[i] % 6);
            if (alteredRolls[i] > 6)
                alteredRolls[i] = alteredRolls[i] - 6;
        }

        StringBuilder report = new StringBuilder();

        for (int j = 0; j < numberOfDice; ++j){
            report.append(unalteredRolls[j]);
            if (j < numberOfDice - 1)
                report.append(", ");
        }

        report.append("Altered Rolls: ");
        for (int k = 0; k < numberOfDice; ++k){
            report.append(alteredRolls[k]);
            if (k < numberOfDice - 1)
                report.append(", ");
        }

        Command c = report.length() == 0 ? new NullCommand() : new Chatter.DisplayText(GameModule.getGameModule().getChatter(), report.toString());
        ((Command)c).execute();
        GameModule.getGameModule().sendAndLog(c);

        return alteredRolls;
    }
    protected int[] DR(int nDice, int nSides) {
        int[] rawRolls = new int[nDice];

        for(int i = 0; i < nDice; ++i) {
            Random ran = new Random();
            int roll = ran.nextInt(nSides) + 1;
            rawRolls[i] = roll;
        }

        return rawRolls;
    }

    public void removeFrom(Buildable parent) {
        if (parent instanceof GameModule) {
            GameModule gameModule = (GameModule) parent;

            // Remove the button from the toolbar
            gameModule.getToolBar().remove(throwDieButton);
        }
    }

    // Creates a mask that indicates what animation indexes (the number just to the right of the die color letter in the folder) bring hesitant die animations
    private HashMap<Integer, HashMap<Integer, ArrayList<Integer>>> CreateHesitantDieFolderBuilder(String path){
        HashMap<Integer, HashMap<Integer, ArrayList<Integer>>> folderNameBuilder = new HashMap<>();
        try {
            InputStream inputStream = dataArchive.getInputStream(path);
            BufferedReader reader = new BufferedReader(new InputStreamReader(inputStream));
            String line;
            System.out.println("BufferedReader created: " + reader);
            while ((line = reader.readLine()) != null){
                System.out.println("Line content: " + line);
                String[] parts = line.split("/");
                int animationIndex = Integer.parseInt(parts[0]);
                int result = Integer.parseInt(parts[2]);
                int rejectedResult = Integer.parseInt(parts[1]);
                System.out.println("Animation: " + animationIndex + "/ result: " + result + "/ rejected result: " + rejectedResult);
                if (!folderNameBuilder.containsKey(animationIndex)) {
                    folderNameBuilder.put(animationIndex, new HashMap<>()); // is a hesitant die animation
                    for (int i = 1; i <= 6; i++) {
                        folderNameBuilder.get(animationIndex).put(i, new ArrayList<Integer>());
                    }
                }
                folderNameBuilder.get(animationIndex).get(result).add(rejectedResult);
            }
        }catch(IOException e){

        }
        System.out.println("Before printing");
        for (int i = 1; i <= 5; i++) {
            for (int k = 1; k <= 6; k++) {
                System.out.println("Number of animation: " + i +
                        " brings the following patterns for /'/" + folderNameBuilder.get(i).get(k) +
                        "/'/ result : " + k);
            }
        }
        return folderNameBuilder;
        /*JarURLConnection j = null;
        try {
            URL imagesFolder = dataArchive.getURL(HESITANT_RED_DIE_FOLDER_PATH);
            System.out.println("Image URL: " + imagesFolder);
            j = (JarURLConnection)imagesFolder.openConnection();
            Enumeration<JarEntry> e = j.getJarFile().entries();
            Pattern hesitantDieFolderPattern = Pattern.compile("^[A-Za-z]\\d+_\\d_\\d$");
            hesitantDiceFolderIndexes = new HashMap<>();

            while (e.hasMoreElements()){
                JarEntry entry = e.nextElement();

                if (entry.getName().startsWith(HESITANT_RED_DIE_FOLDER_PATH) && !entry.getName().endsWith(HESITANT_RED_DIE_FOLDER_PATH) && entry.isDirectory()){
                    System.out.println("Enumerate images in folder: " + entry.getName());
                    String folderName = entry.getName();
                    folderName = folderName.substring(0, folderName.length() - 1);
                    System.out.println("folderName after slash removal: " + folderName);
                    folderName = folderName.substring(HESITANT_RED_DIE_FOLDER_PATH.length()); // concatenation is causing memory problems
                    System.out.println("folder name: " + folderName);
                    Matcher matcher1 = hesitantDieFolderPattern.matcher(folderName);
                    if (matcher1.matches()){
                        String[]parts = folderName.split("_");
                        int animationIndex = Integer.parseInt(parts[0].substring(1));
                        int result = Integer.parseInt(parts[2]);
                        hesitantDiceFolderIndexes
                                .computeIfAbsent(animationIndex, k -> new HashMap<>())
                                .computeIfAbsent(result, k -> new ArrayList<>())
                                .add("_" + parts[1]);
                    }
                }
            }

        }catch (IOException e){
            e.printStackTrace();
        }finally{
            if (j != null){
                try{
                    j.getJarFile().close();
                } catch (IOException e){
                    e.printStackTrace();
                }
            }
        }

        System.out.println("Hashmap length: " + hesitantDiceFolderIndexes.size());
        for (int i = 0; i < hesitantDiceFolderIndexes.size(); i++) {
            for (int k = 1; k <= 6; k++) {
                HashMap<Integer, ArrayList<String>> patterns = hesitantDiceFolderIndexes.get(i);
                List<String> p = patterns.get(k);
                String s = p.get(0);
                System.out.println("Number of animation: " + i +
                        " brings the following patterns for /'/" + s +
                        "/'/ result : " + k);
            }
        }*/
    }

    @Override
    public Command decode(String s) {
        return null;
    }
    @Override
    public String encode(Command command){
        return null;
    }

    @Override
    public String[] getAttributeNames(){
        return new String[]{"AnimatedDice"};
    }
    @Override
    public void setAttribute(String attribute, Object object){
        attribute = "AnimatedDice";
        object = new AnimatedDice();
    }

    @Override
    public String getAttributeValueString(String value){
        return "AnimatedDice";
    }

    @Override
    public HelpFile getHelpFile(){
        HelpFile help = new HelpFile();
        return help;
    }
    @Override
    public Class<?>[] getAllowableConfigureComponents() {
        return new Class[]{AnimatedDice.class};
    }

    public class DelayedActionButton extends JButton {
        private boolean mouseButtonPressed = false;
        private ActionListener delayedActionListener;

        public DelayedActionButton(String buttonText, ActionListener delayedActionListener) {
            super();
            this.delayedActionListener = delayedActionListener;
            this.setText(buttonText);
            setupMouseListener();
        }

        private void setupMouseListener() {
            addMouseListener(new MouseAdapter() {
                java.util.Timer timer;
                @Override
                public void mousePressed(MouseEvent e) {
                    System.out.println("Mouse pressed action inside DelayedActionButton class: NEW ROLL");
                    System.out.println("isImageVisible: " + isImageVisible + " / isAnimationInProgress: " + isAnimationInProgress);
                    super.mousePressed(e);
                    mouseButtonPressed = true;
                    if (!isImageVisible && !isAnimationInProgress) { // doesn't execute when pressed to hide the dices (dice images are still visible)
                        setCursor(dieCursor);
                        playSounds(shakingDiceAudioData);
                        mouseBiasFactor = new int[NUMBER_OF_DICE]; // We'll the number of factors correspondent to the number of dice;
                        Arrays.fill(mouseBiasFactor, 1);
                        final int[] counter = new int[]{0}; // Use of single element array in order to be able to change it inside runnable.

                        timer = new java.util.Timer();
                        timer.schedule(new TimerTask() {
                            @Override
                            public void run() {
                                System.out.println("Mouse Position: " + MouseInfo.getPointerInfo().getLocation());

                                mouseBiasFactor[counter[0]] += MouseInfo.getPointerInfo().getLocation().x + MouseInfo.getPointerInfo().getLocation().y;
                                if (mouseBiasFactor[counter[0]] > 10000)
                                    mouseBiasFactor[counter[0]] = mouseBiasFactor[counter[0]] - 10000;

                                if (counter[0] == mouseBiasFactor.length - 1) {
                                    counter[0] = 0;
                                } else {
                                    counter[0] = counter[0] + 1;
                                }
                                System.out.println("Bias " + counter[0] + " = " + mouseBiasFactor[counter[0]]);
                            }
                        }, 0, 10);
                    }
                }


                @Override
                public void mouseReleased(MouseEvent e) {
                    super.mouseReleased(e);
                    setCursor(Cursor.getDefaultCursor());
                    if (mouseButtonPressed && isEnabled()) {
                        shouldStopFlag = true;
                        timer.cancel();
                        delayedActionListener.actionPerformed(new ActionEvent(this, ActionEvent.ACTION_PERFORMED, ""));
                    }
                    mouseButtonPressed = false;
                }
            });
        }
    }
}


